CREATE DATABASE IF NOT EXISTS nip
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

CREATE DATABASE IF NOT EXISTS eladmin
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

GRANT ALL PRIVILEGES ON nip.* TO 'nip'@'%';
GRANT ALL PRIVILEGES ON eladmin.* TO 'nip'@'%';
FLUSH PRIVILEGES;
