CREATE DATABASE IF NOT EXISTS arte
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

CREATE DATABASE IF NOT EXISTS nip
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_unicode_ci;

GRANT ALL PRIVILEGES ON arte.* TO 'arte'@'%';
GRANT ALL PRIVILEGES ON nip.* TO 'arte'@'%';
FLUSH PRIVILEGES;
