# Spring \u5E94\u7528\u914D\u7F6E
spring.application.name=NobodyIsPerfect
# \u65E5\u5FD7\u914D\u7F6E
logging.config=classpath:log4j2.xml
log.path=/usr/local/data/log/NobodyIsPerfect
log.fileName=NobodyIsPerfect
# \u4E1A\u52A1\u7EBF\u7A0B\u6C60\u914D\u7F6E
threadPool.business.coreSize=5
threadPool.business.maxSize=50
threadPool.business.keepAliveTime=300
threadPool.business.queueSize=1024
# ============= Druid \u6570\u636E\u6E90\u914D\u7F6E start =============
spring.datasource.druid.db-type=com.alibaba.druid.pool.DruidDataSource
# \u6700\u5C0F\u8FDE\u63A5\u6570
spring.datasource.druid.min-idle=5
# \u6700\u5927\u8FDE\u63A5\u6570
spring.datasource.druid.max-active=10
# \u8FDE\u63A5\u6709\u6548\u6027\u68C0\u6D4B\u65F6\u95F4
spring.datasource.druid.time-between-eviction-runs-millis=60000
# \u8FDE\u63A5\u5728\u6C60\u4E2D\u6700\u5C0F\u751F\u5B58\u7684\u65F6\u95F4
spring.datasource.druid.min-evictable-idle-time-millis=300000
# \u8FDE\u63A5\u5728\u6C60\u4E2D\u6700\u5927\u751F\u5B58\u7684\u65F6\u95F4
spring.datasource.druid.max-evictable-idle-time-millis=900000
spring.datasource.druid.test-while-idle=true
spring.datasource.druid.test-on-borrow=false
spring.datasource.druid.test-on-return=false
# \u68C0\u6D4B\u8FDE\u63A5\u662F\u5426\u6709\u6548
spring.datasource.druid.validation-query=select 1
# \u914D\u7F6E\u76D1\u63A7\u7EDF\u8BA1
spring.datasource.druid.webStatFilter.enabled=true
spring.datasource.druid.stat-view-servlet.enabled=true
spring.datasource.druid.stat-view-servlet.url-pattern=/druid/*
spring.datasource.druid.stat-view-servlet.reset-enable=false
spring.datasource.druid.stat-view-servlet.login-username=admin
spring.datasource.druid.stat-view-servlet.login-password=be83ea12
spring.datasource.druid.filter.stat.enabled=true
# \u8BB0\u5F55\u6162SQL
spring.datasource.druid.filter.stat.log-slow-sql=true
spring.datasource.druid.filter.stat.slow-sql-millis=1000
spring.datasource.druid.filter.stat.merge-sql=true
spring.datasource.druid.filter.wall.config.multi-statement-allow=true
# \u83B7\u53D6\u8FDE\u63A5\u8D85\u65F6\u65F6\u95F4
spring.datasource.druid.max-wait=5000
# ============= Druid \u6570\u636E\u6E90\u914D\u7F6E end =============
# ============= \u7F13\u5B58 \u6570\u636E\u6E90\u914D\u7F6E start =============
cache.cache-type=redis
# \u7F13\u5B58\u626B\u63CF\u5305\uFF0C\u591A\u4E2A\u5305\u7528\u82F1\u6587\u9017\u53F7\u5206\u9694
cache.scan-packages=com.nip.app.pojo,com.nip.ai.pojo.model
cache.default.expire=60000
cache.default.max-size=65536
cache.default.cache-key-prefix=NIP
# ============= \u7F13\u5B58 \u6570\u636E\u6E90\u914D\u7F6E end =============
# JWT \u914D\u7F6E
# \u53C2\u89C1 WebSecurityProperties \u7C7B
jwt.header=Authorization
# \u4EE4\u724C\u524D\u7F00
jwt.token-start-with=Bearer
# \u5FC5\u987B\u4F7F\u7528\u6700\u5C1188\u4F4D\u7684Base64\u5BF9\u8BE5\u4EE4\u724C\u8FDB\u884C\u7F16\u7801
jwt.base64-secret-key=3LQ9b6V0dgGihq1sMyNDcJM0XXXH4PZQYjYpNRvyKV5Q2xSeeuWznSB+K+8hH4KQmmdamqbfIRkU0jKhnvNlcb9b
# \u4EE4\u724C\u8FC7\u671F\u65F6\u95F4 \u6B64\u5904\u5355\u4F4D/\u6BEB\u79D2 \uFF0C\u9ED8\u8BA4 2 \u5C0F\u65F6\uFF0C\u53EF\u5728\u6B64\u7F51\u7AD9\u751F\u6210 https://www.convertworld.com/zh-hans/time/milliseconds.html
jwt.token-validity-in-seconds=7200000
# \u5728\u7EBF\u7528\u6237key
jwt.online-key='nip_online:'
# \u9A8C\u8BC1\u7801
jwt.code-key='nip_code:'
# token \u7EED\u671F\u68C0\u67E5\u65F6\u95F4\u8303\u56F4\uFF08\u9ED8\u8BA4 30 \u5206\u949F\uFF0C\u5355\u4F4D\u9ED8\u8BA4\u6BEB\u79D2\uFF09\uFF0C\u5728 token \u5373\u5C06\u8FC7\u671F\u7684\u4E00\u6BB5\u65F6\u95F4\u5185\u7528\u6237\u64CD\u4F5C\u4E86\uFF0C\u5219\u7ED9\u7528\u6237\u7684 token \u7EED\u671F
jwt.detect=1800000
# \u7EED\u671F\u65F6\u95F4\u8303\u56F4\uFF0C\u9ED8\u8BA4 1 \u5C0F\u65F6\uFF0C\u8FD9\u91CC\u5355\u4F4D\u6BEB\u79D2
jwt.renew=3600000
# \u9ED8\u8BA4\u5BC6\u7801
jwt.default-password=arte@2026
# \u767B\u5F55\u76F8\u5173\u914D\u7F6E
# \u767B\u5F55\u7F13\u5B58
login.cache-enable=true
# \u662F\u5426\u9650\u5236\u5355\u7528\u6237\u767B\u5F55
login.single-login=true
# \u9A8C\u8BC1\u7801\u7C7B\u578B\u914D\u7F6E \u67E5\u770B LoginProperties \u7C7B
login.login-code.code-type=arithmetic
# \u767B\u5F55\u56FE\u5F62\u9A8C\u8BC1\u7801\u6709\u6548\u65F6\u95F4/\u5206\u949F
login.login-code.expiration=2
# \u9A8C\u8BC1\u7801\u5BBD\u5EA6
login.login-code.width=111
# \u9A8C\u8BC1\u7801\u9AD8\u5EA6
login.login-code.height=36
# \u5185\u5BB9\u957F\u5EA6
login.login-code.length=2
# \u5B57\u4F53\u540D\u79F0\uFF0C\u4E3A\u7A7A\u5219\u4F7F\u7528\u9ED8\u8BA4\u5B57\u4F53\uFF0C\u5982\u9047\u5230\u7EBF\u4E0A\u4E71\u7801\uFF0C\u8BBE\u7F6E\u5176\u4ED6\u5B57\u4F53\u5373\u53EF
login.login-code.font-name=
# \u5B57\u4F53\u5927\u5C0F
login.login-code.font-size=25
